### ISSUE TITLE
Add Jetbrains as Swag sponsor

### ISSUE THREAD

**Issue by prathamesh-sonpatki** [deccanrubyconf/deccanrubyconf.github.io#18]
@anuja-joshi or @Shwetakale can you add logos from https://resources.jetbrains.com/assets/jetbrains/jetbrains_logos.zip to our website under Sponsors.

Jetbrains is giving us five Rubymine licences for the attendees.Create a new section as **Friends** and it there.

**Comment by Shwetakale** [comment]
@prathamesh-sonpatki https://resources.jetbrains.com/assets/jetbrains/jetbrains_logos.zip returns 404

**Comment by prathamesh-sonpatki** [comment]
Lol, use this https://www.jetbrains.com/company/brand/#section=images-logos

**Comment by prathamesh-sonpatki** [comment]
Please add https://media.pragprog.com/images/cms/logos/Bookshelf_4in.png as well.
