### ISSUE TITLE
Speaker images are compressed / stretched

### ISSUE THREAD

**Issue by swanandp** [deccanrubyconf/deccanrubyconf.github.io#19]
See Aditya and Shaunak's pics. They don't look good.  I think removing "height" on the image would fix it, re-sizing the images might also be needed.

**Comment by shaunakpp** [comment]
I've fixed the images on my fork, do you want me to send a pull request? 

![image](https://user-images.githubusercontent.com/3170078/28105358-c16c3938-66fc-11e7-9646-3dcd2100103c.png)

![image](https://user-images.githubusercontent.com/3170078/28105381-d87c1e0e-66fc-11e7-9c48-ea101aa1c76b.png)

**Comment by prathamesh-sonpatki** [comment]
@shaunakpp Sure!
