### ISSUE TITLE
Add venue page

### ISSUE THREAD

**Issue by prathamesh-sonpatki** [deccanrubyconf/deccanrubyconf.github.io#23]
Similar to http://www.gophercon.in/venue/

**Comment by Shwetakale** [comment]
@prathamesh-sonpatki @anuja-joshi We need to think about Pati for this page

**Comment by prathamesh-sonpatki** [comment]
"Amchi shakha kuthe hi nahi"

**Comment by vipulnsward** [comment]
Lol

Vipul A.M.
+91-8149-204995

**Comment by anuja-joshi** [comment]
"Apeksha v padatrane ithe kadhavit" (original "Nirasha v padatrane ithe kadhavit")

**Comment by prathamesh-sonpatki** [comment]
"Magnya v padatrane" ~ "Demands and shoes"

**Comment by swanandp** [comment]
"अपेक्षा व पादत्राणे येथेच काढावीत" आवडतयं, परंतु "आमची इतरत्र कुठेही शाखा नाही" समर्पक आहे

**Comment by vipulnsward** [comment]
😱 🙀 😱 🙀 😱 🙀 😱 🙀 😱 🙀 😱 🙀 😱 🙀 
😱 🙀 😱 🙀 😱 🙀 😱 🙀 😱 🙀 😱 🙀 😱 🙀 
😱 🙀 😱 🙀 😱 🙀 😱 🙀 😱 🙀 😱 🙀 😱 🙀 

Online marathi classes.

**Comment by prathamesh-sonpatki** [comment]
"डोकं आणि पादत्राणे इथे ठेवूनच आत जा "

**Comment by shailesh-kalamkar** [comment]
For talks - समोरील वक्ता हा ठरलेल्या विषयावरच बोलेल निरर्थक विनोदाच्या अपेक्षा करू नयेत

For T-shirt - माझ्या टीशर्टवरील लोगो दुसऱ्याच्या टीशर्टच्या लोगोपेक्षा फिका आहे सारख्या तक्रारी चालणार नाही 

😄

**Comment by anildigital** [comment]
Some more for the conference

- होऊ दे तोटा, प्रायोजक आहे मोठा!
- इथे परिषदेच्या ट्विट्स स्वीकारल्या जातील. हॅशटॅग #deccanrubyconf  
- होऊ दे भाषण! चर्चा तर होणारच! जागतिक!
- होऊद्या तोऱ्यात, भाषण लई  जोरात!
- जे जगात झालं ते पुण्यात होणार!
- प्रश्न विचार करूनच विचारा आणि जपून 
- कृपया येत जाता दार हळुच बंद करावे 
- इथे कचरा टाकल्यास तुमचे बिल्ड फाटेल!
- भाषण न आवडल्यास आम्ही जबाबदार नाही! 
- काल रुबी शिकलात, आज रुबी शिका, उदयापण रुबी
- परिषदेचे नियम पाळा, आयोजकांची बोलणी टाळा!
- अलंकारिक भाषा वापरून वेळ घालवू नये. सरळ मुद्यावर बोला!
- पत्ता विचारू नये, अपमान होईल.
- फक्त सल्ले दिले जातील! घेतले जाणार नाहीत
- इथे पंगत व्यवस्था नाही! उभे राहून स्वतःचे स्वतः खायला घ्यावे! अन्न खाली सांडवू नये! दंड होईल 
- वायफाय न चालल्यास! स्वतःच्या मोबाईलचा हॉटस्पॉट वापरावा! आयोजकांना त्रास देऊ नये
- लघु भाषण पाच मिनिटांवर गेल्यास दंड होईल! वेळ जपून वापरावा!

**Comment by shailesh-kalamkar** [comment]
दक्खन परिषद 😃

**Comment by tachyons** [comment]
ഇത് കൊള്ളാലോ

**Comment by rohitsiddha** [comment]
On venue page - 
पत्ता शोधण्यासाठी तुमच्या फोन मधील मॅप चा उपयोग करावा.. उगीच आयोजकांना फोन करून त्रास देऊ नये.

**Comment by swanandp** [comment]
@tachyons  നിങ്ങൾക്ക് ഒന്നും നഷ്ടപ്പെടില്ല, ഉറപ്പുണ്ട്.

**Comment by rohitsiddha** [comment]
दिलेल्या पत्त्यावर वेळेवर न पोहोचल्यास अन्यथा कोणत्याही कारणास्तव पैसे परत दिले जाणार नाहीत. 
- हुकुमावरून

**Comment by anuja-joshi** [comment]
@Shwetakale 

![venue](https://user-images.githubusercontent.com/5124042/28526323-d68a73a0-70a4-11e7-96dc-218ee7107232.png)
