### ISSUE TITLE
Change 2017 to 2018 in the image

### ISSUE THREAD

**Issue by smtalimett** [deccanrubyconf/deccanrubyconf.github.io#30]
![download](https://user-images.githubusercontent.com/18298741/36506211-e9d8f0a2-177b-11e8-9ab1-b65397f69833.png)

**Comment by prathamesh-sonpatki** [comment]
@Shwetakale _A Please also fix the twitter cover image: https://twitter.com/deccanrubyconf

**Comment by Shwetakale** [comment]
@prathamesh-sonpatki I don't have access to twitter account.

**Comment by prathamesh-sonpatki** [comment]
We just need to change the year from 2017 to 2018

**Comment by prathamesh-sonpatki** [comment]
@Shwetakale Is this done?
