### ISSUE TITLE
Add Rounak Sharma as speaker

### ISSUE THREAD

**Issue by prathamesh-sonpatki** [deccanrubyconf/deccanrubyconf.github.io#47]
Also remove Tony, he is not able to come.

Talk details:

Title: World of CLI (command line apps) with Ruby

Details:

Ever wonder how these CLI apps work? Whether it is a simple UNIX terminal or Git or Rubocop everything is so fast and powerful. Ever thought why system admins like CLI applications more than GUI for their work? Do you want to make your own personal CLI application?

Yes? Cool then, let’s dive.

![img_20180113_125443 1](https://user-images.githubusercontent.com/621238/43071991-23ae5d70-8e92-11e8-8a61-2b6fe303f4c9.jpg)

**Comment by SwatiJadhav46** [comment]
@prathamesh-sonpatki What is the twitter handle of Rounak Sharma?

**Comment by SwatiJadhav46** [comment]
Never mind. Got it.

**Comment by prathamesh-sonpatki** [comment]
Bio:

A passionate software developer who uses Ruby to express in code is what defines me.

I am in the field of Web-development form past 3 years and I am loving it. Currently, I am a pursuing my undergraduate in Computer Science and working as a software developer in a company(Namyata). I provide services in Web-development and DevOps. When I am not coding you will probably find me on a football field.

Please I to He when actually adding it :)

**Comment by SwatiJadhav46** [comment]
Ok. Thanks.
