### ISSUE TITLE
Add Amura as Digital Sponsor

### ISSUE THREAD

**Issue by smtalimett** [deccanrubyconf/deccanrubyconf.github.io#5]
Their logo is here - http://rubyconfindia.org/assets/images/sponsors/amura.png

**Comment by prathamesh-sonpatki** [comment]
@Shwetakale Can you work on this?

**Comment by Shwetakale** [comment]
@prathamesh-sonpatki Yes, I will. @smtalim We need an image with white background like we have for BigBinary and Josh.  

Above image will not go with theme.

**Comment by prathamesh-sonpatki** [comment]
@Shwetakale It loooks good to me as of now: http://www.deccanrubyconf.org/
