### ISSUE TITLE
Add Trusting Social as Party sponsor

### ISSUE THREAD

**Issue by prathamesh-sonpatki** [deccanrubyconf/deccanrubyconf.github.io#52]
![logo_trustingsocial](https://user-images.githubusercontent.com/621238/43353680-bb3461cc-925b-11e8-9444-d3c4f6a5936c.png)

**Comment by prathamesh-sonpatki** [comment]
Please hold off on this.

**Comment by prathamesh-sonpatki** [comment]
@SwatiJadhav46 We can go ahead with this now

**Comment by SwatiJadhav46** [comment]
@prathamesh-sonpatki This will look like:

![deccan rubyconf 2018](https://user-images.githubusercontent.com/16590944/43390053-ea0dd8e2-940a-11e8-9ef3-0435d841e1fd.png)

Do we have logo with either white background or with blue and white combination?

**Comment by Shwetakale** [comment]
@SwatiJadhav46 You can apply ```white-image-bg``` class to image. This will apply white background to image same as Amura's logo
