### ISSUE TITLE
Please update the sponsorship document with the one here

### ISSUE THREAD

**Issue by smtalimett** [deccanrubyconf/deccanrubyconf.github.io#6]
[drbc_2017_sponsorship.pdf](https://github.com/deccanrubyconf/deccanrubyconf.github.io/files/878917/drbc_2017_sponsorship.pdf)

**Comment by prathamesh-sonpatki** [comment]
@Shwetakale Can you take care of this?

**Comment by prathamesh-sonpatki** [comment]
Updated
