### ISSUE TITLE
Add section for past conferences

### ISSUE THREAD

**Issue by anuja-joshi** [deccanrubyconf/deccanrubyconf.github.io#69]

**Comment by sonamvg** [comment]
Can you please share data for this?

**Comment by prathamesh-sonpatki** [comment]
We have a reference page for rubyconfindia https://www.rubyconfindia.org/previous-conference/

**Comment by sonamvg** [comment]
But we do not have website links to previous years' conferences as per my understanding. Do we want just the blocks for years and venue(Hotel name as all are in the same city)?

**Comment by prathamesh-sonpatki** [comment]
We have links.
2018.deccanrubyconf.org
2017.deccanrubyconf.org
2016.deccanrubyconf.org
2015.deccanrubyconf.org
2014.deccanrubyconf.org
