### ISSUE TITLE
Make "menu" link more prominent

### ISSUE THREAD

**Issue by prathamesh-sonpatki** [deccanrubyconf/deccanrubyconf.github.io#74]
https://monosnap.com/file/27dcN0jUtYZn9bwmxtUk3suso2soA4

**Comment by sonamvg** [comment]
Font size : X-large https://monosnap.com/file/9GcWmMecs0TXWmZwezil4wkdWw3XSR

Font size: Large https://monosnap.com/file/1d1U4waXuTtqQ6pjaDiqTUM0pwHQBY

How prominent do we want it?

**Comment by prathamesh-sonpatki** [comment]
X-large looks okey
