### ISSUE TITLE
Add speaker  Nadia Odunayo as keynote speaker

### ISSUE THREAD

**Issue by prathamesh-sonpatki** [deccanrubyconf/deccanrubyconf.github.io#77]
Bio:

Nadia is Founder and CEO at The StoryGraph  a website for avid readers. Before that, she co-directed Ignition Works, a company that helps enterprise teams run their cloud platforms. She previously worked at Pivotal and originally learnt to code at Makers Academy in London. She maintains speakerline.io in her spare time.

Pic:

![image](https://user-images.githubusercontent.com/621238/61170872-0555ed80-a58d-11e9-88b7-b696b54be958.png)

**Comment by sonamvg** [comment]
Speaker added. Do we need to add "Keynote Speaker" separately, like a header or something?

**Comment by prathamesh-sonpatki** [comment]
Yup, let's add `keynote` text
