### ISSUE TITLE
Add speaker Rohas Nagpal as keynote speaker

### ISSUE THREAD

**Issue by prathamesh-sonpatki** [deccanrubyconf/deccanrubyconf.github.io#78]
![rohas_nagpal_hi-res](https://user-images.githubusercontent.com/621238/61170883-2585ac80-a58d-11e9-80e1-3711accfdfb0.jpg)

Bio:

Blockchain architect (Primechain), co-founder (Asian School of Cyber Laws), public speaker, author (18 books & whitepapers), retired hacker & cyber crime investigator.

**Comment by sonamvg** [comment]
Speaker added. Bio is too short. Doesn't align well with other speakers. Can we add something?

**Comment by prathamesh-sonpatki** [comment]
Bio:

Blockchain architect (Primechain), co-founder (Asian School of Cyber Laws), public speaker, retired hacker & cyber crime investigator. Authored 18 books & whitepapers, He manages the Global Cyber Law Database and Blockchain Security Controls and maintains the Blockchain Blog on medium.com.

@sonamvg Does this look good?
