### ISSUE TITLE
Add speaker Kapil Bhosale

### ISSUE THREAD

**Issue by prathamesh-sonpatki** [deccanrubyconf/deccanrubyconf.github.io#79]
Bio:

My name is Kapil, a Ruby developer for the past 6 years. Co-founder of ruby on rails development shop named 'Decision Tree Labs', located in Pune. I worked mostly on Web app development with Ruby on Rails. My areas of interest include image processing, distributed and parallel computing. I love sports, trekking, travel, and food.
![kapil](https://user-images.githubusercontent.com/621238/61170899-57970e80-a58d-11e9-94c9-45911cfbdc68.jpeg)

**Comment by sonamvg** [comment]
Speaker added. Bio : Tense and language in not in sync with other, especially keynote speakers. Keep as is or change?

**Comment by prathamesh-sonpatki** [comment]
Let's change bio to third person everywhere.
