### ISSUE TITLE
Add Tim Riley as Keynote Speaker

### ISSUE THREAD

**Issue by smtalimett** [deccanrubyconf/deccanrubyconf.github.io#8]
Tim is a partner at Australian design agency Icelab, and a core developer of dry-rb. He’s excited by small libraries, first-class functions, and pushing forward web app development with Ruby.
![3134](https://cloud.githubusercontent.com/assets/18298741/24635705/b83baa5e-18f2-11e7-8443-f309560e4c88.jpg)

**Comment by smtalimett** [comment]
Tim's photo not visible.

**Comment by Shwetakale** [comment]
@smtalimett Fixed this
