### ISSUE TITLE
Add speaker Iqbal Farabi

### ISSUE THREAD

**Issue by prathamesh-sonpatki** [deccanrubyconf/deccanrubyconf.github.io#80]
Bio:

I am a teacher, developer, and now a system engineer at Gojek. Before joining Gojek, I worked for 8 years a Ruby developer and taught Ruby to fresh graduates on pro-bono basis in Indonesia.

Now, at Gojek I work as part of Gojek Cloud Foundation team which focuses on developing containers based infrastructure for Gojek. Beside my main work, I write curriculum for Go Academy, teach at Gojek internal engineering bootcamp, and speak at local and international conferences such as Tech in Asia Jakarta (2016), RubyConf Malaysia (2018), KubeCon + CloudNativeCon Shanghai (2018), and KubeCon + CloudNativeCon Europe (2019).

**Comment by sonamvg** [comment]
Speaker added.
Bio is too lengthy.
Twitter handle not found.
Image missing.

**Comment by prathamesh-sonpatki** [comment]
Bio:

I am a teacher, developer, and now a system engineer at Gojek. Before joining Gojek, I worked for 8 years a Ruby developer and taught Ruby to fresh graduates on pro-bono basis in Indonesia.
Now, at Gojek I work as part of Gojek Cloud Foundation team which focuses on developing containers based infrastructure for Gojek.

Twitter:

https://twitter.com/iqbal_farabi

Image:

https://pbs.twimg.com/profile_images/1102218420051800064/55bvPDZX_400x400.jpg
