### ISSUE TITLE
Add speaker Laura Kirby

### ISSUE THREAD

**Issue by prathamesh-sonpatki** [deccanrubyconf/deccanrubyconf.github.io#81]
Laura is a software engineer at IBM Aspera. She is currently working on a full-stack web application that processes and manages big data. In her spare time, she volunteers for Bridge Foundry, a non-profit that aims to diversify the tech industry. When she isn’t thinking about code, she can be found practicing gymnastics or hosting friends for board games.

![laura](https://user-images.githubusercontent.com/621238/61170918-a3e24e80-a58d-11e9-88ea-9b4db2dacef2.jpeg)

**Comment by sonamvg** [comment]
Speaker added.
Twitter handle not found.

**Comment by prathamesh-sonpatki** [comment]
https://twitter.com/kirby_laura
