### ISSUE TITLE
Add speaker Ratnadeep Deshmane

### ISSUE THREAD

**Issue by prathamesh-sonpatki** [deccanrubyconf/deccanrubyconf.github.io#82]
Bio

I am Ratnadeep aka rtdp, a software craftsman, an entrepreneur and working with Ruby and Ruby on Rails since past 10 years. I am founder of Rails consulting company - BetaCraft Technologies. Please find me to discuss anything related to - Ruby, remote working, digital nomading and travelling.

**Comment by sonamvg** [comment]
Speaker added. Please share image.

**Comment by prathamesh-sonpatki** [comment]
He didn't send image, please get it from https://www.rubyconfindia.org/
