### ISSUE TITLE
Add speaker Prashant Chaudhari

### ISSUE THREAD

**Issue by prathamesh-sonpatki** [deccanrubyconf/deccanrubyconf.github.io#83]
Bio:

I lead the Engineering Team at Jombay. Jombay is one of the fastest growing and highly recognised talent assessment and development companies in India.  I have been leading a team of around 15 developers to build next generation assessment and development products using sophisticated technologies like RoR, NodeJS, AngularJS, Android, iOS, Postgres, MongoDB etc. I have tried my hands on venturing a start-up of my own a few years back.

**Comment by sonamvg** [comment]
Speaker added. Please share image and Twitter profile.

**Comment by prathamesh-sonpatki** [comment]
Twitter:

https://twitter.com/prchaudhari_007

Image should be in our assets directory. He didn't send new image.
