### ISSUE TITLE
Add somewhere (?) Tim's workshop details

### ISSUE THREAD

**Issue by smtalimett** [deccanrubyconf/deccanrubyconf.github.io#9]
# Next generation web apps with dry-rb

Found yourself tangled up in hard-to-maintain code? Been building app after app in the same way and never finding a way to make significant improvements? Vaunted object-oriented design principles proving too elusive or hard to apply? Thinking maybe it’s time to leave Ruby (_gasp!_) for something different?

If you’ve answered yes to any of these questions, this workshop is for you!

Come along and learn how to build a new generation of Ruby web app with [dry-rb](#): an app that is robust, cleanly architected, and just as easy to build now as it will be to maintain later.

You’ll discover how to:

- Apply functional programming principles to Ruby applications
- Model your application as a series of data transformations
- Use dependency injection to take simple components and compose them to build larger pieces of functionality 
- Use strict typing to model your domain data
- Validate user input with clarity and precision
- Build an explicit persistence API with rom-rb
- Use monads to safely manage complex behaviour and improve failure handling
- Model complex behaviour as business transactions
- Separate high-level application concerns into distinct layers
- Write clearer, faster tests for all parts of an application

And then you’ll put these concepts to use in building your own application with dry-rb.

At the end of the day, you’ll have made some real steps towards levelling up as a software developer. You’ll have explored a different paradigm in application design, practiced working with many new gems (15 at least count!), and hopefully found a new enthusiasm for Ruby and how you can wield it to write better, cleaner code.

This workshop is intended for developers with some experience working with Ruby. You’ll need your own laptop and a ready-to-go Ruby development environment.

# Bio

Tim is a partner at Australian design and development agency Icelab, a co-founder and core developer of dry-rb, and a core developer of rom-rb. He’s been working exclusively with this stack for nearly 2 years, and is excited about advancing the state of web development in Ruby.

**Comment by smtalimett** [comment]
The venue for the workshop is:

Josh Software 
Address: A13/14 Sunflower Building, 5th Floor, 
Survey No. 77/1, Mahalunge Baner Road, 
Baner, Pune - 411 045, 
Maharashtra, India.

Time: 10 am to 5 pm
Lunch and two times tea/coffee+cookies will be provided.

**Comment by Shwetakale** [comment]
@smtalimett Do we want details on site or just abstract?

**Comment by smtalimett** [comment]
For GCI17 we had separate pages like http://www.gophercon.in/go-workshop/

**Comment by Shwetakale** [comment]
@smtalimett @prathamesh-sonpatki I think we should add an abstract of the workshop on the page and give a link to "more details" which will open pdf in the new tab. 

Adding separate page like GC17 might not go with the theme. Thoughts?

**Comment by prathamesh-sonpatki** [comment]
@Shwetakale Check last year's site locally, it has all the info on same page.

**Comment by Shwetakale** [comment]
@prathamesh-sonpatki Yes I checked that but last time we had the only a couple of lines on the page. Other option could be open details in modal on click of "read more"

**Comment by Shwetakale** [comment]
Added Tim as workshop conductor. Yet to add details in schedule.

**Comment by prathamesh-sonpatki** [comment]
http://www.deccanrubyconf.org/workshops
