### ISSUE TITLE
Change background color

### ISSUE THREAD

**Issue by sonamvg** [deccanrubyconf/deccanrubyconf.github.io#96]
https://user-images.githubusercontent.com/51998541/62365672-444ee180-b542-11e9-81b5-4b5a366a165a.png

https://user-images.githubusercontent.com/51998541/62365687-503aa380-b542-11e9-8e72-55591cf97571.png

https://user-images.githubusercontent.com/51998541/62365952-1c13b280-b543-11e9-9b6a-84e6cebd26b0.png

https://monosnap.com/file/HhKD6dINOQqvfuQBJ8SXeCQevkDFuV

https://monosnap.com/file/JBbB3mTyvZIJIqhukaBMmHnIDV6goh

**Comment by sonamvg** [comment]
https://visme.co/blog/website-color-schemes/  for more combinations.

**Comment by prathamesh-sonpatki** [comment]
@anuja-joshi

**Comment by vipulnsward** [comment]
Lets do https://user-images.githubusercontent.com/51998541/62365952-1c13b280-b543-11e9-9b6a-84e6cebd26b0.png as that matches the logo and past themes/ is more vibrant
